export const PROVIDER_ENDPOINT_CONFLICT_CODE = "PROVIDER_ENDPOINT_CONFLICT";
export const PROVIDER_ENDPOINT_WRITE_READ_INCONSISTENCY_CODE =
  "PROVIDER_ENDPOINT_WRITE_READ_INCONSISTENCY";
export const ENDPOINT_REFERENCED_BY_ENABLED_PROVIDERS_CODE =
  "ENDPOINT_REFERENCED_BY_ENABLED_PROVIDERS";
