export const PROVIDER_BATCH_PATCH_ERROR_CODES = {
  INVALID_INPUT: "INVALID_INPUT",
  NOTHING_TO_APPLY: "NOTHING_TO_APPLY",
  PREVIEW_EXPIRED: "PREVIEW_EXPIRED",
  PREVIEW_STALE: "PREVIEW_STALE",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  UNDO_EXPIRED: "UNDO_EXPIRED",
  UNDO_CONFLICT: "UNDO_CONFLICT",
  UNDO_STALE: "UNDO_STALE",
} as const;

export const SENSITIVE_PROVIDER_BATCH_UNDO_KEYS: ReadonlySet<string> = new Set([
  "proxyUrl",
  "mcpPassthroughUrl",
]);

export type ProviderBatchPatchErrorCode =
  (typeof PROVIDER_BATCH_PATCH_ERROR_CODES)[keyof typeof PROVIDER_BATCH_PATCH_ERROR_CODES];
