export const PUBLIC_STATUS_INTERVAL_OPTIONS = [5, 15, 30, 60] as const;
export const PUBLIC_STATUS_INTERVAL_SET = new Set<number>(PUBLIC_STATUS_INTERVAL_OPTIONS);
export const MAX_PUBLIC_STATUS_RANGE_HOURS = 168;
